spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/event-service-db
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    user:
      name: admin
      password: admin